#!/bin/sh
set -e

# create project dir
if [ -n "$PROJECT_WORKDIR" ]; then
   mkdir -p "$PROJECT_WORKDIR"
   cd "$PROJECT_WORKDIR"
fi

# add key to user dir
if [ -n "$PROJECT_RSA" ]; then
   mkdir -p ~/.ssh
   cp $PROJECT_RSA ~/.ssh/id_rsa
fi

## install project
if [ -n "$PROJECT_VCS" ]; then
    git clone -b $PROJECT_BRANCH $PROJECT_VCS $PROJECT_PATH
fi

exec "$@"
