#!/bin/sh
set -e

# create project dir
if [ -n "$PROJECT_WORKDIR" ]; then
   mkdir -p "$PROJECT_WORKDIR"
   cd "$PROJECT_WORKDIR"
fi

# add key to user dir
mkdir -p ~/.ssh 
[ -z "$PROJECT_VCS_HOST" ] echo "\n$PROJECT_VCS_RSA" >> ~/.ssh/config
[ -z "$PROJECT_VCS_RSA" ] echo "\n\tStrictHostKeyChecking no"
[ -z "$PROJECT_VCS_RSA" ] echo "\n\tUserKnownHostsFile /dev/null"
[ -z "$PROJECT_VCS_RSA" ] echo "\n\tIdentityFile $PROJECT_VCS_RSA" >> ~/.ssh/config
# add key to user dir
if [ -n "$PROJECT_VCS_RSA" ]; then
   cp $PROJECT_RSA ~/.ssh/id_rsa
fi

## install project
if [ -n "$PROJECT_VCS" ]; then
    git clone -b $PROJECT_BRANCH $PROJECT_VCS $PROJECT_PATH
fi

exec "$@"
